import { readSceneContext, useSceneInteractions } from "./scene-companion.js";
import { useCompanionPersonality } from "./use-companion-effects.js";
import { menuLimit } from "../feature-registry.js";
import { useFeatureRegistry } from "./use-feature-registry.js";
import { useCompanionEffects } from "./use-companion-effects.js";
import { renderPanels } from "./render-panels.js";
import { usePetState } from "./use-pet-state.js";
import { useTaskPresence } from "./use-task-presence.js";
import { usePetLayout } from "./use-pet-layout.js";
import { usePetMotion } from "./use-pet-motion.js";
import { usePetConfig } from "./use-pet-config.js";
import { usePetData } from "./use-pet-data.js";
import { usePetMenu } from "./use-pet-menu.js";
import { usePetPointer } from "./use-pet-pointer.js";
import { useCareActions } from "./use-care-actions.js";
import { renderOrbs } from "./render-orbs.js";
import { createPanelParts } from "./panel-parts.js";
import { renderMascot } from "./render-mascot.js";
/**
 * @description Compose mascot state, behavior and feature panels.
 * @param {object} dependencies Explicit runtime and state dependencies.
 * @returns {object} Public values for the composing component.
 */
export function createPet({
  useHarnessUpdate = () => null,
  usePreferences,
  useRef,
  useEffect,
  DEFAULTS,
  IDLE,
  useState,
  FEATURE_REGISTRY: BUILTIN_FEATURES,
  React,
  ensureTaskRuntime,
  clamp,
  useLayoutEffect,
  liveViewport,
  bubbleOutline,
  useCallback,
  readStore,
  POS_KEY,
  writeStore,
  ASSET_BASE,
  pick,
  taskRuntime,
  injectCss,
  SET_KEY,
  I18N,
  normalizeConfig,
  greetingFor,
  GROW_KEY,
  localHour,
  controls,
  layoutFor,
  LABEL_GAP,
  HINT_KEY,
  DRAG_THRESHOLD,
  t,
  ICONS,
  h,
  fieldLabel,
  weatherIcon,
  LocalClock,
  icon,
  PanelSelect,
  SchedulerSettings,
  RealtimeSettings,
  RewardSettings,
  DesktopSettings,
  PREF_DEFAULTS,
}) {
  return function Pet({ onPlaybackReady } = {}) {
    const { prefs, locale, update: updatePrefs, theme, reduced } = usePreferences();
    const harnessUpdate = useHarnessUpdate(React);
    const FEATURE_REGISTRY = useFeatureRegistry({
      React,
      builtins: BUILTIN_FEATURES,
      showGitHub: prefs.showGitHub,
      showTask: prefs.showTask,
      icon,
      h,
    });

    const petState = usePetState({
      useRef,
      prefs,
      reduced,
      useEffect,
      DEFAULTS,
      IDLE,
      useState,
      FEATURE_REGISTRY,
      React,
    });
    const {
      prefsRef,
      balanceRequest,
      rootRef,
      aRef,
      frontRef,
      timerRef,
      bubbleTimerRef,
      cfgRef,
      dragRef,
      stateRef,
      busyRef,
      lastCareRef,
      lastSeenRef,
      workingSinceRef,
      GROWRef,
      ARCRef,
      orbGeomRef,
      page,
      setPage,
      pageRef,
      pageTimerRef,
      lastPanelRef,
      visibleCountRef,
      ready,
      setReady,
      setTip,
      taskView,
      setTaskView,
      setTaskHovered,
      setTaskVisible,
      hoverTimer,
      fitSurfacesRef,
      bubble,
      accordionName,
      panel,
      setPanel,
      inventory,
      setInventory,
      inventoryBusy,
      setInventoryBusy,
      inventoryBusyRef,
      pendingResource,
      orbOpen,
      setOrbOpen,
      setViewportTick,
      meta,
      setMeta,
      city,
      setCity,
      balanceView,
      setBalanceView,
      weatherView,
      setWeatherView,
      weatherRequest,
      growthView,
      setGrowthView,
    } = petState;

    const { enterTask, leaveTask } = useTaskPresence({
      useRef,
      useEffect,
      ensureTaskRuntime,
      setTaskView,
      taskView,
      setTaskVisible,
      clamp,
      prefs,
      hoverTimer,
      setTaskHovered,
    });
    const { moveTo, applyVisual } = usePetLayout({
      useEffect,
      setViewportTick,
      useLayoutEffect,
      rootRef,
      currentRef: petState.currentRef,
      ARCRef,
      liveViewport,
      cfgRef,
      clamp,
      bubbleOutline,
      dragRef,
      fitSurfacesRef,
      useCallback,
      prefsRef,
      readStore,
      POS_KEY,
      writeStore,
    });
    const sceneContextRef = useRef(null);
    sceneContextRef.current = () =>
      readSceneContext(petState, readStore, GROW_KEY);
    const { play, playMoment, playScene, cancelHover, speak, scheduleNext } =
      usePetMotion({
        ...petState,
        useRef,
        useCallback,
        useEffect,
        ASSET_BASE,
        onPlaybackReady,
        applyVisual,
        prefs,
        reduced,
        pick,
        IDLE,
        taskRuntime,
        sceneContextRef,
      });
    const animationControls = useSceneInteractions({
      React,
      h,
      state: petState,
      prefs,
      reduced,
      SearchSelect: controls.SearchSelect,
      playMoment,
      playScene,
    });
    const { greet, greeting } = useCompanionPersonality({
      React,
      meta,
      prefsRef,
      t,
      baseGreeting: greetingFor,
      cfgRef,
      playScene,
      taskView,
      balanceView,
      panel,
      prefs,
      reduced,
      playMoment,
      speak,
      bubble,
      ready,
    });
    usePetConfig({
      useEffect,
      injectCss,
      readStore,
      SET_KEY,
      setCity,
      ASSET_BASE,
      GROWRef,
      ARCRef,
      I18N,
      prefsRef,
      cfgRef,
      normalizeConfig,
      applyVisual,
      frontRef,
      aRef,
      setReady,
      play,
      setMeta,
      greetingFor: greeting,
      speak,
      setTip,
      timerRef,
      bubbleTimerRef,
    });
    const {
      acceptInventory,
      refreshInventory,
      setFreeInteractions,
      loadBalance,
      loadWeather,
      loadGrowth,
      saveCity,
    } = usePetData({
      useCallback,
      useRef,
      setInventory,
      ASSET_BASE,
      useEffect,
      inventoryBusyRef,
      setInventoryBusy,
      speak,
      GROWRef,
      cfgRef,
      readStore,
      GROW_KEY,
      workingSinceRef,
      busyRef,
      writeStore,
      ready,
      lastSeenRef,
      prefsRef,
      lastCareRef,
      greet,
      localHour,
      balanceRequest,
      setBalanceView,
      controls,
      city,
      weatherRequest,
      setWeatherView,
      locale,
      I18N,
      panel,
      setGrowthView,
      SET_KEY,
      setCity,
    });
    const { closeOrb, toggleOrb, cyclePage, togglePanel, backToMenu } =
      usePetMenu({
        useCallback,
        cfgRef,
        clamp,
        prefsRef,
        ARCRef,
        layoutFor,
        liveViewport,
        visibleCountRef,
        rootRef,
        LABEL_GAP,
        orbGeomRef,
        setOrbOpen,
        setViewportTick,
        useLayoutEffect,
        orbOpen,
        prefs,
        pageTimerRef,
        pageRef,
        setPage,
        setPanel,
        panel,
        FEATURE_REGISTRY,
        useEffect,
        ready,
        readStore,
        HINT_KEY,
        writeStore,
        speak,
        lastPanelRef,
        loadBalance,
        loadWeather,
        refreshInventory,
        loadGrowth,
        playMoment,
        busyRef,
      });
    const { onPointerDown, onPointerMove, onPointerUp } = usePetPointer({
      ready,
      enterTask,
      rootRef,
      dragRef,
      prefsRef,
      DRAG_THRESHOLD,
      play,
      cfgRef,
      moveTo,
      clamp,
      GROWRef,
      writeStore,
      POS_KEY,
      readStore,
      GROW_KEY,
      busyRef,
      scheduleNext,
      stateRef,
      timerRef,
      pick,
      toggleOrb,
    });
    const { feed, interact } = useCareActions({
      useCallback,
      useRef,
      inventoryBusyRef,
      GROWRef,
      cfgRef,
      closeOrb,
      speak,
      pendingResource,
      readStore,
      GROW_KEY,
      busyRef,
      setInventoryBusy,
      ASSET_BASE,
      acceptInventory,
      pick,
      play: playMoment,
      loadGrowth,
      prefsRef,
      t,
      useEffect,
      ready,
    });
    const effects = useCompanionEffects({
      React,
      inventory,
      playMoment,
      cancelHover,
      prefs,
      reduced,
      cfgRef,
      orbOpen,
      panel,
    });
    const cfg = cfgRef.current;
    cfg.ui.arc.pageSize = menuLimit(prefs.menuLimit);

    const { arcCfg, side, geom, stockCount, orbs } = renderOrbs({
      updateAvailable: harnessUpdate?.status?.available || harnessUpdate?.status?.restartRequired,
      hoverFeature: effects.hoverFeature,
      leaveFeature: effects.leaveFeature,
      cfg,
      orbGeomRef,
      inventory,
      I18N,
      FEATURE_REGISTRY,
      lastPanelRef,
      togglePanel,
      feed,
      ARCRef,
      page,
      t,
      ICONS,
      cyclePage,
      visibleCountRef,
      h,
      orbOpen,
      closeOrb,
      speak,
    });
    const { disclosure, metric, updatedAt, cityForm, panelHead, panelShell } =
      createPanelParts({
        h,
        ICONS,
        controls,
        accordionName,
        t,
        I18N,
        fieldLabel,
        city,
        saveCity,
        backToMenu,
      });
    const panelEl = renderPanels({
      harnessUpdate,
      animationControls,
      panel,
      h,
      taskRuntime,
      taskView,
      setPanel,
      rootRef,
      panelShell,
      balanceView,
      panelHead,
      ICONS,
      t,
      loadBalance,
      controls,
      fieldLabel,
      prefs,
      I18N,
      updatedAt,
      weatherView,
      loadWeather,
      weatherIcon,
      metric,
      LocalClock,
      disclosure,
      cityForm,
      growthView,
      loadGrowth,
      refreshInventory,
      inventory,
      inventoryBusy,
      feed,
      stockCount,
      interact,
      icon,
      PanelSelect,
      updatePrefs,
      FEATURE_REGISTRY,
      setFreeInteractions,
      SchedulerSettings,
      RealtimeSettings,
      RewardSettings,
      DesktopSettings,
      POS_KEY,
      applyVisual,
      PREF_DEFAULTS,
    });
    return renderMascot({
      React,
      ...petState,
      overlay: effects.overlay,
      onPointerDown,
      onPointerMove,
      onPointerUp,
      taskRuntime,
      h,
      prefs,
      arcCfg,
      geom,
      enterTask,
      leaveTask,
      locale,
      theme,
      reduced,
      side,
      toggleOrb,
      orbs,
      panelEl,
      controls,
    });
  };
}
